#!/usr/bin/env python
from os import system, listdir
from os.path import isfile, join, expanduser
from random import choice
from PIL import Image

# calculate dimensions of all screens together
def calculate_wallpaper_geometry(monitors):
    hor = 0
    ver = 0
    for monitor in monitors:
        hor = max(hor, monitor[0] + monitor[2])
        ver = max(ver, monitor[1] + monitor[3])
    return (hor, ver)

# This script expects you to have wallpapers in "~/Pictures/wallpapers"
wallpaper_directory = expanduser("~/Pictures/wallpapers");
all_images = []
for image in listdir(wallpaper_directory):
    if isfile(join(wallpaper_directory, image)):
        if image.lower().endswith((".png", ".jpg")):
            all_images.append(image)


# Set geometry of your monitors [offset_x, offset_y, width, height]
monitors = [
    [0,     0,  1920,   1080],
    [1920,  0,  1680,   1050]
]

# create wallpaper and paste images to it
wallpaper = Image.new('RGB', calculate_wallpaper_geometry(monitors), (0, 0, 0))

for monitor in monitors:
    image = Image.open(join(wallpaper_directory, choice(all_images))) # load random wallpaper
    image = image.resize((monitor[2], monitor[3]))
    wallpaper.paste(image, (monitor[0], monitor[1]))


# save wallpaper to cache and run feh
cache_directory = expanduser("~/.cache")
wallpaper.save(join(cache_directory, "screen_wallpaper.jpg"), "JPEG")
system(f"feh --no-xinerama --bg-fill {join(cache_directory, 'screen_wallpaper.jpg')}")
